server:
  port: 8084
  tomcat:
    max-threads: 10000
    max-connections: 80000
    accept-count: 4000

spring:
  application:
    name: fihws-spring-boot-starter
  rabbitmq:
    host: 47.96.75.125
    port: 5672
    username: admin
    password: fih-foxconn123!@#
    #开启发送失败返回
    publisher-returns: true
    #开启发送确认
    publisher-confirms: true
    listener:
      simple:
        #指定最小的消费者数量.
        concurrency: 2
        #指定最大的消费者数量.
        max-concurrency: 2
        #开启ack
        acknowledge-mode: auto
        #开启ack
      direct:
        acknowledge-mode: auto
     #支持消息的确认与返回
    template:
      receive-timeout: 30000s #消费端接收的响应时间
      reply-timeout: 30000s #发送端等待接收消费端给出return msg的时间 相当于在message同步时，发送并消费成功的时间。
      retry:
        enabled: true

push.config.queue: queue_push1


logging:
  config: classpath:logback-spring.xml
  path: logs/

